name: 'Vilicus Scan'
description: 'Scans container images for vulnerabilities using Vilicus'
author: 'Ederson Brilhante'
inputs:
  image:
    description: 'image reference'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x job.sh
        ./job.sh
      env:
        IMAGE: ${{ inputs.image }}
      shell: bash
branding:
  icon: 'shield'
  color: 'green'
