name: 'Vilicus Scan'
description: 'Scans container images for vulnerabilities using Vilicus'
author: 'Ederson Brilhante'
inputs:
  image:
    description: 'image reference'
    required: true
  template:
    description: 'template output'
    required: false
    default: /opt/vilicus/contrib/sarif.tpl
  config:
    description: 'config file'
    required: false
    default: /opt/vilicus/configs/conf.yaml
  output:
    description: 'output file name'
    required: false
    default: results.sarif
runs:
  using: "composite"
  steps:
    - id: scan
      run: |
        wget -O ${{ github.action_path }}/job.sh https://raw.githubusercontent.com/edersonbrilhante/vilicus/develop/scripts/run-job.sh
        chmod +x ${{ github.action_path }}/job.sh
        ${{ github.action_path }}/job.sh
      env:
        IMAGE: ${{ inputs.image }}
        TEMPLATE: ${{ inputs.template }}
        CONFIG: ${{ inputs.config }}
        OUTPUT: /artifacts/${{ inputs.output }}
      shell: bash
branding:
  icon: 'shield'
  color: 'purple'