name: 'Vilicus Scan'
description: 'Scans container images for vulnerabilities using Vilicus'
author: 'Ederson Brilhante'
inputs:
  image:
    description: 'image reference'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        wget -O ${{ github.action_path }}/job.sh https://raw.githubusercontent.com/edersonbrilhante/vilicus/develop/scripts/run-job.sh
        chmod +x ${{ github.action_path }}/job.sh
        ${{ github.action_path }}/job.sh
      env:
        IMAGE: ${{ inputs.image }}
        TEMPLATE: /opt/vilicus/contrib/sarif.tpl
        CONFIG: /opt/vilicus/configs/conf.yaml
        OUTPUT: /artifacts/results.sarif
      shell: bash
branding:
  icon: 'shield'
  color: 'green'